# Generated by Django 6.0.3 on 2026-04-04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("requested_tenure_months", models.PositiveIntegerField()),
                ("stated_income", models.DecimalField(decimal_places=2, max_digits=15)),
                ("purpose", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("evaluating", "Evaluating"),
                            ("evaluated", "Evaluated"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                (
                    "ai_recommendation",
                    models.CharField(
                        blank=True,
                        choices=[("approve", "Approve"), ("reject", "Reject")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "ai_risk_level",
                    models.CharField(
                        blank=True,
                        choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("ai_score", models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ("decision_reasoning", models.TextField(blank=True, null=True)),
                ("admin_decision_note", models.TextField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loan_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
