# Generated by Django 6.0.3 on 2026-04-04 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_loanrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudFeedbackRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='transaction', max_length=30)),
                ('predicted_label', models.BooleanField(default=False)),
                ('predicted_probability', models.DecimalField(decimal_places=4, max_digits=5)),
                ('predicted_risk_level', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20, null=True)),
                ('actual_outcome', models.CharField(choices=[('fraud', 'Fraud'), ('legitimate', 'Legitimate'), ('unconfirmed', 'Unconfirmed')], default='unconfirmed', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_feedback_record', to='payments.loanrequest')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_feedback_record', to='payments.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_feedback_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=80)),
                ('pattern_key', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_alerts', to='payments.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_scope', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=20)),
                ('category', models.CharField(choices=[('loan_update', 'Loan Update'), ('fraud_alert', 'Fraud Alert'), ('admin_decision', 'Admin Decision')], max_length=30)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('delivery_status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('read', 'Read')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_loan_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_notifications', to='payments.loanrequest')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_notifications', to='payments.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='UserTrustProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_score', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('flagged_transactions', models.PositiveIntegerField(default=0)),
                ('high_risk_transactions', models.PositiveIntegerField(default=0)),
                ('flagged_ratio', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('behavior_change_count', models.PositiveIntegerField(default=0)),
                ('last_event_type', models.CharField(blank=True, max_length=60, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
